/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AccountType = IDL.Variant({
  'Bank' : IDL.Null,
  'Cash' : IDL.Null,
  'Savings' : IDL.Null,
});
export const Account = IDL.Record({
  'id' : IDL.Text,
  'currentBalance' : IDL.Float64,
  'name' : IDL.Text,
  'accountType' : AccountType,
  'openingBalance' : IDL.Float64,
});
export const CategoryType = IDL.Variant({
  'Income' : IDL.Null,
  'Expense' : IDL.Null,
});
export const Category = IDL.Record({
  'id' : IDL.Text,
  'categoryType' : CategoryType,
  'name' : IDL.Text,
});
export const SavingsGoal = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'deadline' : IDL.Opt(IDL.Nat),
  'targetAmount' : IDL.Float64,
  'currentAmount' : IDL.Float64,
});
export const TransactionType = IDL.Variant({
  'Income' : IDL.Null,
  'Expense' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'categoryId' : IDL.Text,
  'transactionType' : TransactionType,
  'accountId' : IDL.Text,
  'receiptNote' : IDL.Text,
  'date' : IDL.Nat,
  'description' : IDL.Text,
  'amount' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const StatementFilter = IDL.Record({
  'accountId' : IDL.Opt(IDL.Text),
  'toDate' : IDL.Opt(IDL.Nat),
  'fromDate' : IDL.Opt(IDL.Nat),
});
export const Statement = IDL.Record({
  'totalExpenses' : IDL.Float64,
  'closingBalance' : IDL.Float64,
  'openingBalance' : IDL.Float64,
  'totalCredits' : IDL.Float64,
  'transactions' : IDL.Vec(Transaction),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAccount' : IDL.Func([IDL.Text], [], []),
  'deleteCategory' : IDL.Func([IDL.Text], [], []),
  'deleteSavingsGoal' : IDL.Func([IDL.Text], [], []),
  'deleteTransaction' : IDL.Func([IDL.Text], [], []),
  'getAccount' : IDL.Func([IDL.Text], [IDL.Opt(Account)], ['query']),
  'getAllAccounts' : IDL.Func([], [IDL.Vec(Account)], ['query']),
  'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getAllSavingsGoals' : IDL.Func([], [IDL.Vec(SavingsGoal)], ['query']),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategory' : IDL.Func([IDL.Text], [IDL.Opt(Category)], ['query']),
  'getSavingsGoal' : IDL.Func([IDL.Text], [IDL.Opt(SavingsGoal)], ['query']),
  'getStatement' : IDL.Func([StatementFilter], [Statement], ['query']),
  'getTransaction' : IDL.Func([IDL.Text], [IDL.Opt(Transaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveAccount' : IDL.Func([Account], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCategory' : IDL.Func([Category], [IDL.Text], []),
  'saveSavingsGoal' : IDL.Func([SavingsGoal], [IDL.Text], []),
  'saveTransaction' : IDL.Func([Transaction], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AccountType = IDL.Variant({
    'Bank' : IDL.Null,
    'Cash' : IDL.Null,
    'Savings' : IDL.Null,
  });
  const Account = IDL.Record({
    'id' : IDL.Text,
    'currentBalance' : IDL.Float64,
    'name' : IDL.Text,
    'accountType' : AccountType,
    'openingBalance' : IDL.Float64,
  });
  const CategoryType = IDL.Variant({
    'Income' : IDL.Null,
    'Expense' : IDL.Null,
  });
  const Category = IDL.Record({
    'id' : IDL.Text,
    'categoryType' : CategoryType,
    'name' : IDL.Text,
  });
  const SavingsGoal = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'deadline' : IDL.Opt(IDL.Nat),
    'targetAmount' : IDL.Float64,
    'currentAmount' : IDL.Float64,
  });
  const TransactionType = IDL.Variant({
    'Income' : IDL.Null,
    'Expense' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'categoryId' : IDL.Text,
    'transactionType' : TransactionType,
    'accountId' : IDL.Text,
    'receiptNote' : IDL.Text,
    'date' : IDL.Nat,
    'description' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const StatementFilter = IDL.Record({
    'accountId' : IDL.Opt(IDL.Text),
    'toDate' : IDL.Opt(IDL.Nat),
    'fromDate' : IDL.Opt(IDL.Nat),
  });
  const Statement = IDL.Record({
    'totalExpenses' : IDL.Float64,
    'closingBalance' : IDL.Float64,
    'openingBalance' : IDL.Float64,
    'totalCredits' : IDL.Float64,
    'transactions' : IDL.Vec(Transaction),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAccount' : IDL.Func([IDL.Text], [], []),
    'deleteCategory' : IDL.Func([IDL.Text], [], []),
    'deleteSavingsGoal' : IDL.Func([IDL.Text], [], []),
    'deleteTransaction' : IDL.Func([IDL.Text], [], []),
    'getAccount' : IDL.Func([IDL.Text], [IDL.Opt(Account)], ['query']),
    'getAllAccounts' : IDL.Func([], [IDL.Vec(Account)], ['query']),
    'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getAllSavingsGoals' : IDL.Func([], [IDL.Vec(SavingsGoal)], ['query']),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategory' : IDL.Func([IDL.Text], [IDL.Opt(Category)], ['query']),
    'getSavingsGoal' : IDL.Func([IDL.Text], [IDL.Opt(SavingsGoal)], ['query']),
    'getStatement' : IDL.Func([StatementFilter], [Statement], ['query']),
    'getTransaction' : IDL.Func([IDL.Text], [IDL.Opt(Transaction)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveAccount' : IDL.Func([Account], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCategory' : IDL.Func([Category], [IDL.Text], []),
    'saveSavingsGoal' : IDL.Func([SavingsGoal], [IDL.Text], []),
    'saveTransaction' : IDL.Func([Transaction], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };