/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Account {
  'id' : string,
  'currentBalance' : number,
  'name' : string,
  'accountType' : AccountType,
  'openingBalance' : number,
}
export type AccountType = { 'Bank' : null } |
  { 'Cash' : null } |
  { 'Savings' : null };
export interface Category {
  'id' : string,
  'categoryType' : CategoryType,
  'name' : string,
}
export type CategoryType = { 'Income' : null } |
  { 'Expense' : null };
export interface SavingsGoal {
  'id' : string,
  'status' : string,
  'name' : string,
  'description' : string,
  'deadline' : [] | [bigint],
  'targetAmount' : number,
  'currentAmount' : number,
}
export interface Statement {
  'totalExpenses' : number,
  'closingBalance' : number,
  'openingBalance' : number,
  'totalCredits' : number,
  'transactions' : Array<Transaction>,
}
export interface StatementFilter {
  'accountId' : [] | [string],
  'toDate' : [] | [bigint],
  'fromDate' : [] | [bigint],
}
export interface Transaction {
  'id' : string,
  'categoryId' : string,
  'transactionType' : TransactionType,
  'accountId' : string,
  'receiptNote' : string,
  'date' : bigint,
  'description' : string,
  'amount' : number,
}
export type TransactionType = { 'Income' : null } |
  { 'Expense' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteAccount' : ActorMethod<[string], undefined>,
  'deleteCategory' : ActorMethod<[string], undefined>,
  'deleteSavingsGoal' : ActorMethod<[string], undefined>,
  'deleteTransaction' : ActorMethod<[string], undefined>,
  'getAccount' : ActorMethod<[string], [] | [Account]>,
  'getAllAccounts' : ActorMethod<[], Array<Account>>,
  'getAllCategories' : ActorMethod<[], Array<Category>>,
  'getAllSavingsGoals' : ActorMethod<[], Array<SavingsGoal>>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategory' : ActorMethod<[string], [] | [Category]>,
  'getSavingsGoal' : ActorMethod<[string], [] | [SavingsGoal]>,
  'getStatement' : ActorMethod<[StatementFilter], Statement>,
  'getTransaction' : ActorMethod<[string], [] | [Transaction]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveAccount' : ActorMethod<[Account], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveCategory' : ActorMethod<[Category], string>,
  'saveSavingsGoal' : ActorMethod<[SavingsGoal], string>,
  'saveTransaction' : ActorMethod<[Transaction], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];