/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Transaction {
    id: string;
    categoryId: string;
    transactionType: TransactionType;
    accountId: string;
    receiptNote: string;
    date: bigint;
    description: string;
    amount: number;
}
export interface Category {
    id: string;
    categoryType: CategoryType;
    name: string;
}
export interface Account {
    id: string;
    currentBalance: number;
    name: string;
    accountType: AccountType;
    openingBalance: number;
}
export interface StatementFilter {
    accountId?: string;
    toDate?: bigint;
    fromDate?: bigint;
}
export interface Statement {
    totalExpenses: number;
    closingBalance: number;
    openingBalance: number;
    totalCredits: number;
    transactions: Array<Transaction>;
}
export interface UserProfile {
    name: string;
}
export interface SavingsGoal {
    id: string;
    status: string;
    name: string;
    description: string;
    deadline?: bigint;
    targetAmount: number;
    currentAmount: number;
}
export enum AccountType {
    Bank = "Bank",
    Cash = "Cash",
    Savings = "Savings"
}
export enum CategoryType {
    Income = "Income",
    Expense = "Expense"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteAccount(accountId: string): Promise<void>;
    deleteCategory(categoryId: string): Promise<void>;
    deleteSavingsGoal(goalId: string): Promise<void>;
    deleteTransaction(transactionId: string): Promise<void>;
    getAccount(accountId: string): Promise<Account | null>;
    getAllAccounts(): Promise<Array<Account>>;
    getAllCategories(): Promise<Array<Category>>;
    getAllSavingsGoals(): Promise<Array<SavingsGoal>>;
    getAllTransactions(): Promise<Array<Transaction>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCategory(categoryId: string): Promise<Category | null>;
    getSavingsGoal(goalId: string): Promise<SavingsGoal | null>;
    getStatement(filter: StatementFilter): Promise<Statement>;
    getTransaction(transactionId: string): Promise<Transaction | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveAccount(account: Account): Promise<string>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveCategory(category: Category): Promise<string>;
    saveSavingsGoal(goal: SavingsGoal): Promise<string>;
    saveTransaction(transaction: Transaction): Promise<string>;
}
import type { Account as _Account, AccountType as _AccountType, Category as _Category, CategoryType as _CategoryType, SavingsGoal as _SavingsGoal, Statement as _Statement, StatementFilter as _StatementFilter, Transaction as _Transaction, TransactionType as _TransactionType, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteAccount(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAccount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAccount(arg0);
            return result;
        }
    }
    async deleteCategory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCategory(arg0);
            return result;
        }
    }
    async deleteSavingsGoal(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSavingsGoal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSavingsGoal(arg0);
            return result;
        }
    }
    async deleteTransaction(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTransaction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTransaction(arg0);
            return result;
        }
    }
    async getAccount(arg0: string): Promise<Account | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccount(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccount(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAccounts(): Promise<Array<Account>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAccounts();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAccounts();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCategories(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCategories();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCategories();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSavingsGoals(): Promise<Array<SavingsGoal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSavingsGoals();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSavingsGoals();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTransactions();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTransactions();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategory(arg0: string): Promise<Category | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategory(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategory(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSavingsGoal(arg0: string): Promise<SavingsGoal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSavingsGoal(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSavingsGoal(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStatement(arg0: StatementFilter): Promise<Statement> {
        if (this.processError) {
            try {
                const result = await this.actor.getStatement(to_candid_StatementFilter_n27(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Statement_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStatement(to_candid_StatementFilter_n27(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Statement_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransaction(arg0: string): Promise<Transaction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransaction(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransaction(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveAccount(arg0: Account): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.saveAccount(to_candid_Account_n32(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveAccount(to_candid_Account_n32(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveCategory(arg0: Category): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCategory(to_candid_Category_n36(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCategory(to_candid_Category_n36(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveSavingsGoal(arg0: SavingsGoal): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSavingsGoal(to_candid_SavingsGoal_n40(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSavingsGoal(to_candid_SavingsGoal_n40(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveTransaction(arg0: Transaction): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.saveTransaction(to_candid_Transaction_n42(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveTransaction(to_candid_Transaction_n42(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AccountType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccountType): AccountType {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Account_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Account): Account {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_CategoryType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CategoryType): CategoryType {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_SavingsGoal_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SavingsGoal): SavingsGoal {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Statement_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Statement): Statement {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Category]): Category | null {
    return value.length === 0 ? null : from_candid_Category_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SavingsGoal]): SavingsGoal | null {
    return value.length === 0 ? null : from_candid_SavingsGoal_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Account]): Account | null {
    return value.length === 0 ? null : from_candid_Account_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Transaction]): Transaction | null {
    return value.length === 0 ? null : from_candid_Transaction_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    categoryType: _CategoryType;
    name: string;
}): {
    id: string;
    categoryType: CategoryType;
    name: string;
} {
    return {
        id: value.id,
        categoryType: from_candid_CategoryType_n12(_uploadFile, _downloadFile, value.categoryType),
        name: value.name
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    name: string;
    description: string;
    deadline: [] | [bigint];
    targetAmount: number;
    currentAmount: number;
}): {
    id: string;
    status: string;
    name: string;
    description: string;
    deadline?: bigint;
    targetAmount: number;
    currentAmount: number;
} {
    return {
        id: value.id,
        status: value.status,
        name: value.name,
        description: value.description,
        deadline: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.deadline)),
        targetAmount: value.targetAmount,
        currentAmount: value.currentAmount
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    categoryId: string;
    transactionType: _TransactionType;
    accountId: string;
    receiptNote: string;
    date: bigint;
    description: string;
    amount: number;
}): {
    id: string;
    categoryId: string;
    transactionType: TransactionType;
    accountId: string;
    receiptNote: string;
    date: bigint;
    description: string;
    amount: number;
} {
    return {
        id: value.id,
        categoryId: value.categoryId,
        transactionType: from_candid_TransactionType_n21(_uploadFile, _downloadFile, value.transactionType),
        accountId: value.accountId,
        receiptNote: value.receiptNote,
        date: value.date,
        description: value.description,
        amount: value.amount
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalExpenses: number;
    closingBalance: number;
    openingBalance: number;
    totalCredits: number;
    transactions: Array<_Transaction>;
}): {
    totalExpenses: number;
    closingBalance: number;
    openingBalance: number;
    totalCredits: number;
    transactions: Array<Transaction>;
} {
    return {
        totalExpenses: value.totalExpenses,
        closingBalance: value.closingBalance,
        openingBalance: value.openingBalance,
        totalCredits: value.totalCredits,
        transactions: from_candid_vec_n18(_uploadFile, _downloadFile, value.transactions)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    currentBalance: number;
    name: string;
    accountType: _AccountType;
    openingBalance: number;
}): {
    id: string;
    currentBalance: number;
    name: string;
    accountType: AccountType;
    openingBalance: number;
} {
    return {
        id: value.id,
        currentBalance: value.currentBalance,
        name: value.name,
        accountType: from_candid_AccountType_n6(_uploadFile, _downloadFile, value.accountType),
        openingBalance: value.openingBalance
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Income: null;
} | {
    Expense: null;
}): CategoryType {
    return "Income" in value ? CategoryType.Income : "Expense" in value ? CategoryType.Expense : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Bank: null;
} | {
    Cash: null;
} | {
    Savings: null;
}): AccountType {
    return "Bank" in value ? AccountType.Bank : "Cash" in value ? AccountType.Cash : "Savings" in value ? AccountType.Savings : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SavingsGoal>): Array<SavingsGoal> {
    return value.map((x)=>from_candid_SavingsGoal_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Account>): Array<Account> {
    return value.map((x)=>from_candid_Account_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Category>): Array<Category> {
    return value.map((x)=>from_candid_Category_n10(_uploadFile, _downloadFile, x));
}
function to_candid_AccountType_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccountType): _AccountType {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_Account_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Account): _Account {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_CategoryType_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CategoryType): _CategoryType {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_Category_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_SavingsGoal_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SavingsGoal): _SavingsGoal {
    return to_candid_record_n41(_uploadFile, _downloadFile, value);
}
function to_candid_StatementFilter_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StatementFilter): _StatementFilter {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionType_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): _TransactionType {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_Transaction_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Transaction): _Transaction {
    return to_candid_record_n43(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    accountId?: string;
    toDate?: bigint;
    fromDate?: bigint;
}): {
    accountId: [] | [string];
    toDate: [] | [bigint];
    fromDate: [] | [bigint];
} {
    return {
        accountId: value.accountId ? candid_some(value.accountId) : candid_none(),
        toDate: value.toDate ? candid_some(value.toDate) : candid_none(),
        fromDate: value.fromDate ? candid_some(value.fromDate) : candid_none()
    };
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    currentBalance: number;
    name: string;
    accountType: AccountType;
    openingBalance: number;
}): {
    id: string;
    currentBalance: number;
    name: string;
    accountType: _AccountType;
    openingBalance: number;
} {
    return {
        id: value.id,
        currentBalance: value.currentBalance,
        name: value.name,
        accountType: to_candid_AccountType_n34(_uploadFile, _downloadFile, value.accountType),
        openingBalance: value.openingBalance
    };
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    categoryType: CategoryType;
    name: string;
}): {
    id: string;
    categoryType: _CategoryType;
    name: string;
} {
    return {
        id: value.id,
        categoryType: to_candid_CategoryType_n38(_uploadFile, _downloadFile, value.categoryType),
        name: value.name
    };
}
function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    name: string;
    description: string;
    deadline?: bigint;
    targetAmount: number;
    currentAmount: number;
}): {
    id: string;
    status: string;
    name: string;
    description: string;
    deadline: [] | [bigint];
    targetAmount: number;
    currentAmount: number;
} {
    return {
        id: value.id,
        status: value.status,
        name: value.name,
        description: value.description,
        deadline: value.deadline ? candid_some(value.deadline) : candid_none(),
        targetAmount: value.targetAmount,
        currentAmount: value.currentAmount
    };
}
function to_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    categoryId: string;
    transactionType: TransactionType;
    accountId: string;
    receiptNote: string;
    date: bigint;
    description: string;
    amount: number;
}): {
    id: string;
    categoryId: string;
    transactionType: _TransactionType;
    accountId: string;
    receiptNote: string;
    date: bigint;
    description: string;
    amount: number;
} {
    return {
        id: value.id,
        categoryId: value.categoryId,
        transactionType: to_candid_TransactionType_n44(_uploadFile, _downloadFile, value.transactionType),
        accountId: value.accountId,
        receiptNote: value.receiptNote,
        date: value.date,
        description: value.description,
        amount: value.amount
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccountType): {
    Bank: null;
} | {
    Cash: null;
} | {
    Savings: null;
} {
    return value == AccountType.Bank ? {
        Bank: null
    } : value == AccountType.Cash ? {
        Cash: null
    } : value == AccountType.Savings ? {
        Savings: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CategoryType): {
    Income: null;
} | {
    Expense: null;
} {
    return value == CategoryType.Income ? {
        Income: null
    } : value == CategoryType.Expense ? {
        Expense: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
